---
Name: download-folder
After: '#assetsflysystem'
---
# see https://docs.silverstripe.org/en/developer_guides/configuration/configuration/
SilverStripe\Assets\Folder:
  extensions:
    - Sunnysideup\DownloadFolder\Extensions\DownloadFolderExtension

SilverStripe\AssetAdmin\Forms\AssetFormFactory:
  extensions:
    - Sunnysideup\DownloadFolder\Extensions\DownloadFolderFileFormFactoryExtension
